DROP TABLE IF EXISTS comments;
DROP SEQUENCE IF EXISTS comments_id_seq;
DROP TABLE IF EXISTS orders_products;
DROP TABLE IF EXISTS orders;
DROP SEQUENCE IF EXISTS orders_id_seq;
DROP TABLE IF EXISTS users;
DROP SEQUENCE IF EXISTS users_id_seq;
DROP TABLE IF EXISTS products;
DROP SEQUENCE IF EXISTS products_id_seq;

CREATE SEQUENCE products_id_seq AS INTEGER START WITH 1;
CREATE TABLE products (
  id          INTEGER GENERATED BY DEFAULT AS SEQUENCE products_id_seq PRIMARY KEY,
  name        LONGVARCHAR NOT NULL,
  price       NUMERIC(10,2),
  color       INTEGER,
  capacity    INTEGER,
  display     LONGVARCHAR,
  description LONGVARCHAR,
  image       LONGVARCHAR
);

CREATE SEQUENCE users_id_seq AS INTEGER START WITH 1;
CREATE TABLE users (
  id          INTEGER GENERATED BY DEFAULT AS SEQUENCE users_id_seq PRIMARY KEY,
  email       LONGVARCHAR NOT NULL UNIQUE,
  password    LONGVARCHAR NOT NULL,
  name        LONGVARCHAR NOT NULL,
  role        INTEGER NOT NULL
);

CREATE SEQUENCE orders_id_seq AS INTEGER START WITH 1;
CREATE TABLE orders (
  id            INTEGER GENERATED BY DEFAULT AS SEQUENCE orders_id_seq PRIMARY KEY,
  total_amount  NUMERIC(10,2) NOT NULL,
  datetime      DATETIME NOT NULL,
  name          LONGVARCHAR NOT NULL,
  email         LONGVARCHAR NOT NULL,
  phone         LONGVARCHAR,
  address       LONGVARCHAR NOT NULL,
  user_id       INTEGER,
  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE TABLE orders_products (
  order_id    INTEGER NOT NULL,
  product_id  INTEGER NOT NULL,
  FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE,
  FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE
);

CREATE SEQUENCE comments_id_seq AS INTEGER START WITH 1;
CREATE TABLE comments (
  id          INTEGER GENERATED BY DEFAULT AS SEQUENCE comments_id_seq PRIMARY KEY,
  product_id  INTEGER NOT NULL,
  author      LONGVARCHAR NOT NULL,
  datetime    TIMESTAMP,
  text        LONGVARCHAR,
  rating      INTEGER,
  FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE
);
